[env]
# Workspace directory to properly resolve artifacts relative paths
# it will always be relative to the workspace and can be rewritten if required
PROJECTS_TOML = { value = "./tests/projects.toml", relative = true, force = false }
